### PR TITLE
Make it work

### PR DESCRIPTION
**Pull request by kyle-query**
This PR will make it possible to run the CrowdStrike and SplunkPy demisto integrations on AWS lambda, with no modifications to their source [*].

I created my own `demistomock.py` which uses some tricks to be a proxy object for a `Demisto` instance. 

[*] Since there were some changes made to the integrations before I began, I made an effort to revert them to their pristine state. There might be some changes I didn't undo though, unintentionally.

### CODE REVIEW

**Comment by abhishek-query** [comment]
> I created my own `demistomock.py` which uses some tricks to be a proxy object for a `Demisto` instance. As far as I can tell, everything works without any edits to the Demisto source files.
> 
> However I am not sure that I returned the original files to their 100% original condition, since they had some edits before I started. I also did not test the SplunkPy driver.

Thanks @kyle-query . I've tested `SplunkPy` which works as expected via lambda. However, I had to change following line for testing:
lambda_function.py line# 38:
`payload  = body`

Also, there is 1 line which was changed by me in DemistoClassApiModule.py line# 387
`data = globals()['__readWhileAvailable']()`
If above line is not changed then below error occurrs:
`
  File "/Users/abhishek/repo/serverless-driver/Packs/ApiModules/Scripts/DemistoClassApiModule/DemistoClassApiModule.py", line 389, in __do
    data = globals()['__readWhileAvailable']()
KeyError: '__readWhileAvailable'
`

Can we set globals() in your `demistomock.py` so that above line is not changed in original demisto source?

**Comment by kyle-query** [comment]
Glad things are working @abhishek-query!

You can probably fix the issue with `__readWhileAvailable` by putting somewhere near the top of either demistomock.py. Be sure to write a comment explaining why this exists, since IDEs probably won’t be able to “find references” to it.

```python
global __readWhileAvailable
__readWhileAvailable = lambda: {‘context’: {}}
```

**Comment by kyle-query** [comment]
@abhishek-query: I've made more changes that resolve that issue. It's more complicated than what we did last week, because `__readWhileAvailable` is used to get the result from `STDOUT` of invoking a function that was called by writing to `STDOUT`. In one scenario, an "integration context" is requested, but in other contexts, some other value would need to be returned. Like you said, this is how drivers interact with the Demisto framework.

I've created our own `Demisto` subclass that overrides some of those functions. Over time we will probably need to override others if they call `__do` or `__do_end`. I've overridden `__do` and `__do_no_res`, which are the central point for communication over STDIN/STDOUT happens. Now it will throw an exception letting us know which method needs to be overridden in our `Demisto` subclass.

**Comment by abhishek-query** [comment]
@kyle-query I referred the latest code but getting below stacktrace along with result.
```
(env) abhishek@admins-MBP serverless-driver % python lambda_function.py
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/local/Cellar/python@3.7/3.7.12_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "lambda_function.py", line 79, in <module>
    result = lambda_handler(event, None)
  File "lambda_function.py", line 45, in lambda_handler
    driver = load_driver(platform, ctx)
  File "lambda_function.py", line 27, in load_driver
    import Packs.CrowdStrikeFalcon.Integrations.CrowdStrikeFalcon.CrowdStrikeFalcon as driver
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abhishek/repo/serverless-driver/Packs/CrowdStrikeFalcon/Integrations/CrowdStrikeFalcon/CrowdStrikeFalcon.py", line 1, in <module>
    import demistomock as demisto
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abhishek/repo/serverless-driver/demistomock.py", line 1, in <module>
    from queryai.demistomock import *
  File "<frozen importlib._bootstrap>", line 1019, in _handle_fromlist
  File "/Users/abhishek/repo/serverless-driver/queryai/demistomock.py", line 43, in _hasattr
    return obj.__hasattr__(attr) # type: ignore
  File "/Users/abhishek/repo/serverless-driver/queryai/demistomock.py", line 55, in __hasattr__
    logger.debug('__hasattr__', attr)
Message: '__hasattr__'
Arguments: ('__path__',)
Starting new HTTPS connection (1): api.crowdstrike.com:443
https://api.crowdstrike.com:443 "POST /oauth2/token HTTP/1.1" 201 1215
{'result': 'ok'}
```

**Comment by kyle-query** [comment]
Should be fixed now, @abhishek-query. It was a call in `demistomock.py` to `logger.debug` which was written incorrectly.

**Comment by abhishek-query** [comment]
@kyle-query yes, the logging issue is fixed. I see below logs during my testing:
```
(env) abhishek@admins-MBP serverless-driver % python lambda_function.py
demistomock.__hasattr__(__path__)
demistomock.__hasattr__(params)
demistomock.__hasattr__(is_debug)
demistomock.__hasattr__(getParam)
demistomock.__hasattr__(is_debug)
Starting new HTTPS connection (1): api.crowdstrike.com:443
https://api.crowdstrike.com:443 "POST /oauth2/token HTTP/1.1" 201 1215
{'result': 'ok'}
```

**Pull request merged**
